-- MySQL Script generated by MySQL Workbench
-- Sat Mar 21 13:15:40 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sahs_scheduler
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sahs_scheduler
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sahs_scheduler` DEFAULT CHARACTER SET utf8 ;
USE `sahs_scheduler` ;

-- -----------------------------------------------------
-- Table `sahs_scheduler`.`instrument`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sahs_scheduler`.`instrument` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `requiredByTeacher` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sahs_scheduler`.`parent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sahs_scheduler`.`parent` (
  `email` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `phone` INT NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`email`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sahs_scheduler`.`teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sahs_scheduler`.`teacher` (
  `email` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  PRIMARY KEY (`email`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sahs_scheduler`.`teacherPlaysInstrument`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sahs_scheduler`.`teacherPlaysInstrument` (
  `id` INT NOT NULL,
  `fk_teacherEmail` VARCHAR(45) NOT NULL,
  `fk_instrumentId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_instrument_has_teacher_teacher1_idx` (`fk_teacherEmail` ASC),
  INDEX `fk_instrument_has_teacher_instrument_idx` (`fk_instrumentId` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_instrumentId`
    FOREIGN KEY (`fk_instrumentId`)
    REFERENCES `sahs_scheduler`.`instrument` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teacherEmail`
    FOREIGN KEY (`fk_teacherEmail`)
    REFERENCES `sahs_scheduler`.`teacher` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sahs_scheduler`.`lesson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sahs_scheduler`.`lesson` (
  `id` INT NOT NULL,
  `fk_teacher` VARCHAR(45) NOT NULL,
  `fk_parent` VARCHAR(45) NOT NULL,
  `fk_instrument` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_teacher_idx` (`fk_teacher` ASC),
  INDEX `fk_parebt_idx` (`fk_parent` ASC),
  INDEX `fk_instrument_idx` (`fk_instrument` ASC),
  CONSTRAINT `fk_teacher`
    FOREIGN KEY (`fk_teacher`)
    REFERENCES `sahs_scheduler`.`teacher` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_parent`
    FOREIGN KEY (`fk_parent`)
    REFERENCES `sahs_scheduler`.`parent` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_instrument`
    FOREIGN KEY (`fk_instrument`)
    REFERENCES `sahs_scheduler`.`instrument` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
